#!/bin/bash
# traefik.sh - Traefik configuration management functions

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Traefik config directory (Coolify default)
TRAEFIK_CONFIG_DIR="/data/coolify/proxy/dynamic"

# Get all Traefik labels from a container
# Usage: get_traefik_labels "container-id"
# Returns: Labels in key=value format, one per line
get_traefik_labels() {
    local container_id="$1"

    if [[ -z "$container_id" ]]; then
        echo -e "${RED}ERROR: Container ID required${NC}" >&2
        return 1
    fi

    # Get all labels starting with traefik.
    docker inspect "$container_id" --format '{{range $k, $v := .Config.Labels}}{{if eq (index (split $k ".") 0) "traefik"}}{{$k}}={{$v}}{{"\n"}}{{end}}{{end}}' 2>/dev/null
}

# Extract service name from Traefik labels
# Usage: extract_service_name "container-id"
# Returns: Traefik service name (e.g., "translation-api-service")
extract_service_name() {
    local container_id="$1"

    if [[ -z "$container_id" ]]; then
        echo -e "${RED}ERROR: Container ID required${NC}" >&2
        return 1
    fi

    # Look for traefik.http.services.<name>.loadbalancer.server.port or similar
    local service_name
    service_name=$(get_traefik_labels "$container_id" | grep -oP 'traefik\.http\.services\.\K[^.]+' | head -n1)

    echo "$service_name"
}

# Extract router names from Traefik labels
# Usage: extract_router_names "container-id"
# Returns: Router names, one per line
extract_router_names() {
    local container_id="$1"

    if [[ -z "$container_id" ]]; then
        echo -e "${RED}ERROR: Container ID required${NC}" >&2
        return 1
    fi

    # Look for traefik.http.routers.<name>
    get_traefik_labels "$container_id" | grep -oP 'traefik\.http\.routers\.\K[^.]+' | sort -u
}

# Check if container has Traefik labels
# Usage: has_traefik_labels "container-id"
# Returns: 0 if has labels, 1 if not
has_traefik_labels() {
    local container_id="$1"

    if [[ -z "$container_id" ]]; then
        return 1
    fi

    local labels
    labels=$(get_traefik_labels "$container_id")

    [[ -n "$labels" ]]
}

# Find existing Traefik dynamic config file for a service
# Usage: find_traefik_config "service-name"
# Returns: Path to config file or empty string
find_traefik_config() {
    local service="$1"

    if [[ -z "$service" ]]; then
        echo -e "${RED}ERROR: Service name required${NC}" >&2
        return 1
    fi

    # Check common naming patterns
    local patterns=(
        "${TRAEFIK_CONFIG_DIR}/${service}.yaml"
        "${TRAEFIK_CONFIG_DIR}/${service}.yml"
        "${TRAEFIK_CONFIG_DIR}/${service}-service.yaml"
        "${TRAEFIK_CONFIG_DIR}/${service}-service.yml"
    )

    for pattern in "${patterns[@]}"; do
        if [[ -f "$pattern" ]]; then
            echo "$pattern"
            return 0
        fi
    done

    # Search for files containing the service name
    if [[ -d "$TRAEFIK_CONFIG_DIR" ]]; then
        local found
        found=$(grep -l "url.*$service" "$TRAEFIK_CONFIG_DIR"/*.yaml "$TRAEFIK_CONFIG_DIR"/*.yml 2>/dev/null | head -n1)
        if [[ -n "$found" ]]; then
            echo "$found"
            return 0
        fi
    fi

    return 1
}

# Extract load balancer URL from config file
# Usage: get_primary_url_from_config "config-file"
# Returns: Primary container URL
get_primary_url_from_config() {
    local config_file="$1"

    if [[ ! -f "$config_file" ]]; then
        return 1
    fi

    # Extract first URL from loadBalancer servers
    grep -oP "url:\s*['\"]?\K[^'\"]+(?=['\"]?)" "$config_file" | head -n1
}

# Check if config already has failover URL
# Usage: config_has_failover "config-file" "failover-name"
# Returns: 0 if already has failover, 1 if not
config_has_failover() {
    local config_file="$1"
    local failover_name="$2"

    if [[ ! -f "$config_file" ]]; then
        return 1
    fi

    grep -q "$failover_name" "$config_file"
}

# Create load balancer config from scratch
# Usage: create_load_balancer_config "service" "primary-url" "failover-url" "health-endpoint" "output-file"
create_load_balancer_config() {
    local service="$1"
    local primary_url="$2"
    local failover_url="$3"
    local health_endpoint="$4"
    local output_file="$5"

    if [[ -z "$service" ]] || [[ -z "$primary_url" ]] || [[ -z "$failover_url" ]]; then
        echo -e "${RED}ERROR: Missing required parameters${NC}" >&2
        return 1
    fi

    # Default health endpoint
    health_endpoint="${health_endpoint:-/health}"

    # Create the YAML config
    cat > "$output_file" <<EOF
# Auto-generated by coolify-zero
# Service: $service
# Generated: $(date '+%Y-%m-%d %H:%M:%S')
# NOTE: Using weighted servers for TRUE FAILOVER (not load balancing)
# Primary weight=100 gets all traffic when healthy
# Failover weight=1 only receives traffic when primary fails health check

http:
  services:
    ${service}-service:
      loadBalancer:
        servers:
          - url: '${primary_url}'
            weight: 100
          - url: '${failover_url}'
            weight: 1
        healthCheck:
          path: ${health_endpoint}
          interval: 10s
          timeout: 3s
EOF

    if [[ $? -eq 0 ]]; then
        echo -e "${GREEN}✓ Created new Traefik config: $output_file${NC}"
        return 0
    else
        echo -e "${RED}✗ Failed to create Traefik config${NC}" >&2
        return 1
    fi
}

# Update existing config to add failover URL
# Usage: update_load_balancer_config "config-file" "failover-url"
update_load_balancer_config() {
    local config_file="$1"
    local failover_url="$2"

    if [[ ! -f "$config_file" ]]; then
        echo -e "${RED}ERROR: Config file not found: $config_file${NC}" >&2
        return 1
    fi

    if [[ -z "$failover_url" ]]; then
        echo -e "${RED}ERROR: Failover URL required${NC}" >&2
        return 1
    fi

    # Backup original
    cp "$config_file" "${config_file}.backup-$(date +%s)"

    # Find the line with the first server URL and add failover after it
    # This uses sed to find "- url:" and add another "- url:" line after it
    local temp_file="${config_file}.tmp"

    awk -v failover="$failover_url" '
    /^[[:space:]]*- url:/ {
        if (!added) {
            # Print the primary URL line
            print
            # Check if next line has weight, if not add it
            getline nextline
            if (nextline !~ /weight:/) {
                # Add weight to primary
                match($0, /^[[:space:]]*/)
                indent = substr($0, RSTART, RLENGTH)
                print indent "  weight: 100"
                print nextline
            } else {
                print nextline
            }
            # Add failover with weight
            match($0, /^[[:space:]]*/)
            indent = substr($0, RSTART, RLENGTH)
            print indent "- url: '\''" failover "'\''"
            print indent "  weight: 1"
            added = 1
            next
        }
    }
    { print }
    ' "$config_file" > "$temp_file"

    if [[ $? -eq 0 ]]; then
        mv "$temp_file" "$config_file"
        echo -e "${GREEN}✓ Updated Traefik config: $config_file${NC}"
        return 0
    else
        echo -e "${RED}✗ Failed to update Traefik config${NC}" >&2
        rm -f "$temp_file"
        return 1
    fi
}

# Restart Traefik proxy container
# Usage: restart_traefik
restart_traefik() {
    local traefik_container="coolify-proxy"

    echo -e "${BLUE}Restarting Traefik proxy...${NC}"

    if ! docker ps --filter "name=${traefik_container}" --format '{{.ID}}' | grep -q .; then
        echo -e "${YELLOW}⚠ Traefik container '${traefik_container}' not found${NC}" >&2
        echo -e "${BLUE}Traefik watches config directory and reloads automatically${NC}"
        return 0
    fi

    # Traefik typically auto-reloads configs, but we can send a signal
    # Instead of full restart, just touch a file to trigger reload
    echo -e "${BLUE}Traefik should auto-reload the config within a few seconds${NC}"

    # Verify Traefik sees the config
    sleep 2
    docker logs --tail 20 "$traefik_container" 2>&1 | grep -i "configuration" | tail -3 || true

    return 0
}

# Main function: Auto-configure Traefik for failover
# Usage: auto_configure_traefik "service" "primary-id" "failover-name" "health-endpoint" "health-port"
auto_configure_traefik() {
    local service="$1"
    local primary_id="$2"
    local failover_name="$3"
    local health_endpoint="$4"
    local health_port="$5"

    if [[ -z "$service" ]] || [[ -z "$primary_id" ]] || [[ -z "$failover_name" ]]; then
        echo -e "${RED}ERROR: Missing required parameters${NC}" >&2
        return 1
    fi

    health_endpoint="${health_endpoint:-/health}"
    health_port="${health_port:-3000}"

    echo -e "\n${BLUE}${BOLD}=== Auto-configuring Traefik ===${NC}"

    # Check if Traefik config directory exists
    if [[ ! -d "$TRAEFIK_CONFIG_DIR" ]]; then
        echo -e "${YELLOW}⚠ Traefik config directory not found: $TRAEFIK_CONFIG_DIR${NC}" >&2
        echo -e "${YELLOW}⚠ Skipping Traefik auto-configuration${NC}" >&2
        echo -e "${BLUE}Run 'coolify-zero traefik $service' for manual setup${NC}"
        return 1
    fi

    # Check if we have write permission
    if [[ ! -w "$TRAEFIK_CONFIG_DIR" ]]; then
        echo -e "${YELLOW}⚠ No write permission to Traefik config directory${NC}" >&2
        echo -e "${YELLOW}⚠ Run with sudo or as root${NC}" >&2
        return 1
    fi

    # Determine primary container URL
    local primary_name
    primary_name=$(get_container_name "$primary_id")
    local primary_url="http://${primary_name}:${health_port}"
    local failover_url="http://${failover_name}:${health_port}"

    echo -e "${BLUE}Primary URL: $primary_url${NC}"
    echo -e "${BLUE}Failover URL: $failover_url${NC}"

    # Find or create config file
    local config_file
    config_file=$(find_traefik_config "$service")

    if [[ -n "$config_file" ]]; then
        echo -e "${BLUE}Found existing config: $config_file${NC}"

        # Check if already has failover
        if config_has_failover "$config_file" "$failover_name"; then
            echo -e "${GREEN}✓ Config already includes failover URL${NC}"
            return 0
        fi

        # Update existing config
        echo -e "${BLUE}Adding failover URL to existing config...${NC}"
        if update_load_balancer_config "$config_file" "$failover_url"; then
            restart_traefik
            return 0
        else
            return 1
        fi
    else
        # Create new config
        config_file="${TRAEFIK_CONFIG_DIR}/${service}.yaml"
        echo -e "${BLUE}Creating new config: $config_file${NC}"

        if create_load_balancer_config "$service" "$primary_url" "$failover_url" "$health_endpoint" "$config_file"; then
            restart_traefik
            echo -e "\n${YELLOW}⚠ NOTE: You may need to configure routers manually${NC}"
            echo -e "${YELLOW}⚠ This config only creates the load balancer service${NC}"
            echo -e "${YELLOW}⚠ Check if your routers point to '${service}-service'${NC}"
            return 0
        else
            return 1
        fi
    fi
}

# Export functions for use in other scripts
export -f get_traefik_labels
export -f extract_service_name
export -f extract_router_names
export -f has_traefik_labels
export -f find_traefik_config
export -f get_primary_url_from_config
export -f config_has_failover
export -f create_load_balancer_config
export -f update_load_balancer_config
export -f restart_traefik
export -f auto_configure_traefik
